FROM node:18-alpine AS builder
WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
ENV NODE_ENV=production
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3126

CMD ["node", "dist/src/index.js"]